// testWorkers.js
import { enqueue } from './src/repositories/jobsRepo.js';
import { startWorkers } from './src/services/worker.js';

// Enqueue a few jobs — unique IDs auto-generated by uuidv4()
enqueue({ command: "echo 'Job A done!'" });
enqueue({ command: "sleep 2 && echo 'Job B done!'" });
enqueue({ command: "sleep 1 && echo 'Job C done!'" });

// Start 2 workers to process them concurrently
startWorkers(2);
